import flattenKeys from 'flat';
import {
  // Base Pallette
  bg,
  fg,
  red,
  yellow,
  orange,
  green,
  blue,
  cyan,
  pink,
  purple,
  // Computed & Utilities
  primary,
  secondary,
  comment,
} from './colors';

// Common
const darkFg = bg.darken(0.5);
const highlight = primary.fade(0.95);
const none = bg.fade(1);
const border = bg.darken(0.7);

// Using
const workbench = {
  activityBar: {
    activeBackground: primary.mix(bg, 1).hexa(),
    activeBorder: primary.hexa(),
    activeFocusBorder: '',
    background: bg.darken(0.2).hexa(),
    border: border.hexa(),
    dropBorder: '',
    foreground: primary.hexa(),
    inactiveForeground: comment.hexa(),
  },
  activityBarBadge: {
    background: primary.hexa(),
    foreground: darkFg.hexa(),
  },
  activityBarItem: {
    settingsProfilesBackground: '',
    settingsProfilesForeground: '',
    settingsProfilesHoverForeground: '',
  },
  badge: {
    background: primary.hexa(),
    foreground: darkFg.hexa(),
  },
  banner: {
    background: '',
    foreground: '',
    iconForeground: '',
  },
  breadcrumb: {
    activeSelectionForeground: '',
    background: '',
    focusForeground: '',
    foreground: '',
  },
  breadcrumbPicker: {
    background: '',
  },
  button: {
    background: '',
    border: '',
    foreground: '',
    hoverBackground: '',
    secondaryBackground: '',
    secondaryForeground: '',
    secondaryHoverBackground: '',
    separator: '',
  },
  charts: {
    blue: '',
    foreground: '',
    green: '',
    lines: '',
    orange: '',
    purple: '',
    red: '',
    yellow: '',
  },
  checkbox: {
    background: '',
    border: '',
    foreground: '',
  },
  commandCenter: {
    activeBackground: '',
    activeForeground: '',
    background: '',
    border: '',
    foreground: '',
    inactiveBorder: '',
    inactiveForeground: '',
  },
  contrastActiveBorder: '',
  contrastBorder: '',
  debugConsole: {
    errorForeground: '',
    infoForeground: '',
    sourceForeground: '',
    warningForeground: '',
  },
  debugConsoleInputIcon: {
    foreground: '',
  },
  debugExceptionWidget: {
    background: '',
    border: '',
  },
  debugIcon: {
    breakpointCurrentStackframeForeground: '',
    breakpointDisabledForeground: '',
    breakpointForeground: '',
    breakpointStackframeForeground: '',
    breakpointUnverifiedForeground: '',
    continueForeground: '',
    disconnectForeground: '',
    pauseForeground: '',
    restartForeground: '',
    startForeground: '',
    stepBackForeground: '',
    stepIntoForeground: '',
    stepOutForeground: '',
    stepOverForeground: '',
    stopForeground: '',
  },
  debugTokenExpression: {
    boolean: '',
    error: '',
    name: '',
    number: '',
    string: '',
    value: '',
  },
  debugToolBar: {
    background: '',
    border: '',
  },
  debugView: {
    exceptionLabelBackground: '',
    exceptionLabelForeground: '',
    stateLabelBackground: '',
    stateLabelForeground: '',
    valueChangedHighlight: '',
  },
  descriptionForeground: '',
  diffEditor: {
    border: '',
    diagonalFill: '',
    insertedLineBackground: '',
    insertedTextBackground: '',
    insertedTextBorder: '',
    removedLineBackground: '',
    removedTextBackground: '',
    removedTextBorder: '',
  },
  diffEditorGutter: {
    insertedLineBackground: '',
    removedLineBackground: '',
  },
  diffEditorOverview: {
    insertedForeground: '',
    removedForeground: '',
  },
  disabledForeground: comment.hexa(),
  dropdown: {
    background: '',
    border: '',
    foreground: '',
    listBackground: '',
  },
  editor: {
    background: bg.hexa(),
    findMatchBackground: secondary.fade(0.6).hexa(),
    findMatchBorder: '',
    findMatchHighlightBackground: secondary.fade(0.8).hexa(),
    findMatchHighlightBorder: '',
    findRangeHighlightBackground: '',
    findRangeHighlightBorder: '',
    focusedStackFrameHighlightBackground: '',
    foldBackground: bg.darken(0.1).hexa(),
    foreground: fg.hexa(),
    hoverHighlightBackground: '',
    inactiveSelectionBackground: '',
    inlineValuesBackground: '',
    inlineValuesForeground: '',
    lineHighlightBackground: highlight.hexa(),
    lineHighlightBorder: '',
    linkedEditingBackground: '',
    rangeHighlightBackground: '',
    rangeHighlightBorder: '',
    selectionBackground: primary.fade(0.65).hexa(),
    selectionForeground: '',
    selectionHighlightBackground: fg.fade(0.85).hexa(),
    selectionHighlightBorder: '',
    snippetFinalTabstopHighlightBackground: '',
    snippetFinalTabstopHighlightBorder: '',
    snippetTabstopHighlightBackground: '',
    snippetTabstopHighlightBorder: '',
    stackFrameHighlightBackground: '',
    symbolHighlightBackground: '',
    symbolHighlightBorder: '',
    wordHighlightBackground: '',
    wordHighlightBorder: '',
    wordHighlightStrongBackground: '',
    wordHighlightStrongBorder: '',
  },
  editorActiveLineNumber: {
    foreground: '',
  },
  editorBracketHighlight: {
    foreground1: '',
    foreground2: '',
    foreground3: '',
    foreground4: '',
    foreground5: '',
    foreground6: '',
    unexpectedBracket: {
      foreground: red.hexa(),
    },
  },
  editorBracketMatch: {
    background: '',
    border: none.hexa(),
  },
  editorBracketPairGuide: {
    activeBackground1: '',
    activeBackground2: '',
    activeBackground3: '',
    activeBackground4: '',
    activeBackground5: '',
    activeBackground6: '',
    background1: '',
    background2: '',
    background3: '',
    background4: '',
    background5: '',
    background6: '',
  },
  editorCodeLens: {
    foreground: '',
  },
  editorCommentsWidget: {
    rangeActiveBackground: '',
    rangeActiveBorder: '',
    rangeBackground: '',
    rangeBorder: '',
    resolvedBorder: '',
    unresolvedBorder: '',
  },
  editorCursor: {
    background: '',
    foreground: fg.hexa(),
  },
  editorError: {
    background: '',
    border: '',
    foreground: '',
  },
  editorGhostText: {
    background: '',
    border: '',
    foreground: '',
  },
  editorGroup: {
    border: border.hexa(),
    dropBackground: highlight.opaquer(0.3).hexa(),
    dropIntoPromptBackground: '',
    dropIntoPromptBorder: '',
    dropIntoPromptForeground: '',
    emptyBackground: '',
    focusedEmptyBorder: '',
  },
  editorGroupHeader: {
    border: '',
    noTabsBackground: '',
    tabsBackground: bg.darken(0.2).hexa(),
    tabsBorder: '',
  },
  editorGutter: {
    addedBackground: green.fade(0.6).hexa(),
    something: 'new',
    background: '',
    commentRangeForeground: '',
    deletedBackground: red.fade(0.6).hexa(),
    foldingControlForeground: '',
    modifiedBackground: secondary.hexa(),
  },
  editorHint: {
    border: '',
    foreground: '',
  },
  editorHoverWidget: {
    background: bg.darken(0.2).hexa(),
    border: none.hexa(),
    foreground: fg.hexa(),
    highlightForeground: '',
    statusBarBackground: '',
  },
  editorIndentGuide: {
    activeBackground: '',
    background: '',
  },
  editorInfo: {
    background: '',
    border: border.hexa(),
    foreground: '',
  },
  editorInlayHint: {
    background: '',
    foreground: '',
    parameterBackground: '',
    parameterForeground: '',
    typeBackground: '',
    typeForeground: '',
  },
  editorLightBulb: {
    foreground: '',
  },
  editorLightBulbAutoFix: {
    foreground: '',
  },
  editorLineNumber: {
    activeForeground: comment.hexa(),
    foreground: comment.hexa(),
  },
  editorLink: {
    activeForeground: '',
  },
  editorMarkerNavigation: {
    background: '',
  },
  editorMarkerNavigationError: {
    background: '',
    headerBackground: '',
  },
  editorMarkerNavigationInfo: {
    background: '',
    headerBackground: '',
  },
  editorMarkerNavigationWarning: {
    background: '',
    headerBackground: '',
  },
  editorOverviewRuler: {
    addedForeground: bg.hexa(),
    background: '',
    border: '',
    bracketMatchForeground: '',
    commonContentForeground: '',
    currentContentForeground: '',
    deletedForeground: bg.hexa(),
    errorForeground: red.hexa(),
    findMatchForeground: secondary.fade(0.8).hexa(),
    incomingContentForeground: '',
    infoForeground: '',
    modifiedForeground: bg.hexa(),
    rangeHighlightForeground: '',
    selectionHighlightForeground: primary.fade(0.8).hexa(),
    warningForeground: '',
    wordHighlightForeground: '',
    wordHighlightStrongForeground: '',
  },
  editorPane: {
    background: '',
  },
  editorRuler: {
    foreground: '',
  },
  editorStickyScroll: {
    background: '',
  },
  editorStickyScrollHover: {
    background: '',
  },
  editorSuggestWidget: {
    background: '',
    border: '',
    focusHighlightForeground: '',
    foreground: '',
    highlightForeground: '',
    selectedBackground: '',
    selectedForeground: '',
    selectedIconForeground: '',
  },
  editorSuggestWidgetStatus: {
    foreground: '',
  },
  editorUnicodeHighlight: {
    background: '',
    border: '',
  },
  editorUnnecessaryCode: {
    border: '',
    opacity: '',
  },
  editorWarning: {
    background: '',
    border: '',
    foreground: '',
  },
  editorWhitespace: {
    foreground: '',
  },
  editorWidget: {
    background: bg.darken(0.2).hexa(),
    border: none.hexa(),
    foreground: fg.hexa(),
    resizeBorder: '',
  },
  errorForeground: red.desaturate(0.3).hexa(),
  extensionBadge: {
    remoteBackground: '',
    remoteForeground: '',
  },
  extensionButton: {
    background: '',
    foreground: '',
    hoverBackground: '',
    prominentBackground: '',
    prominentForeground: '',
    prominentHoverBackground: '',
    separator: '',
  },
  extensionIcon: {
    preReleaseForeground: '',
    sponsorForeground: '',
    starForeground: '',
    verifiedForeground: '',
  },
  focusBorder: none.hexa(),
  foreground: '',
  gitDecoration: {
    addedResourceForeground: green.hexa(),
    conflictingResourceForeground: '',
    deletedResourceForeground: '',
    ignoredResourceForeground: comment.hexa(),
    modifiedResourceForeground: secondary.hexa(),
    renamedResourceForeground: secondary.hexa(),
    stageDeletedResourceForeground: '',
    stageModifiedResourceForeground: secondary.hexa(),
    submoduleResourceForeground: '',
    untrackedResourceForeground: green.hexa(),
  },
  icon: {
    foreground: fg.hexa(),
  },
  input: {
    background: bg.darken(0.35).hexa(),
    border: '',
    foreground: fg.hexa(),
    placeholderForeground: '',
  },
  inputOption: {
    activeBackground: '',
    activeBorder: '',
    activeForeground: '',
    hoverBackground: '',
  },
  inputValidation: {
    errorBackground: '',
    errorBorder: '',
    errorForeground: '',
    infoBackground: '',
    infoBorder: '',
    infoForeground: '',
    warningBackground: '',
    warningBorder: '',
    warningForeground: '',
  },
  interactive: {
    activeCodeBorder: '',
    inactiveCodeBorder: '',
  },
  keybindingLabel: {
    background: '',
    border: '',
    bottomBorder: '',
    foreground: '',
  },
  keybindingTable: {
    headerBackground: '',
    rowsBackground: '',
  },
  list: {
    activeSelectionBackground: highlight.hexa(),
    activeSelectionForeground: primary.hexa(),
    activeSelectionIconForeground: fg.hexa(),
    deemphasizedForeground: comment.hexa(),
    dropBackground: highlight.opaquer(0.3).hexa(),
    errorForeground: red.hexa(),
    filterMatchBackground: red.hexa(),
    filterMatchBorder: '',
    focusAndSelectionOutline: '',
    focusBackground: highlight.hexa(),
    focusForeground: primary.hexa(),
    focusHighlightForeground: primary.hexa(),
    focusOutline: '',
    highlightForeground: primary.hexa(),
    hoverBackground: highlight.hexa(),
    hoverForeground: fg.hexa(),
    inactiveFocusBackground: highlight.hexa(),
    inactiveFocusOutline: '',
    inactiveSelectionBackground: highlight.hexa(),
    inactiveSelectionForeground: fg.hexa(),
    inactiveSelectionIconForeground: fg.hexa(),
    invalidItemForeground: '',
    warningForeground: yellow.hexa(),
  },
  listFilterWidget: {
    background: '',
    noMatchesOutline: '',
    outline: '',
    shadow: '',
  },
  menu: {
    background: '',
    border: '',
    foreground: '',
    selectionBackground: '',
    selectionBorder: '',
    selectionForeground: '',
    separatorBackground: '',
  },
  menubar: {
    selectionBackground: '',
    selectionBorder: '',
    selectionForeground: '',
  },
  merge: {
    border: '',
    commonContentBackground: '',
    commonHeaderBackground: '',
    currentContentBackground: '',
    currentHeaderBackground: '',
    incomingContentBackground: '',
    incomingHeaderBackground: '',
  },
  mergeEditor: {
    change: {
      background: '',
      word: {
        background: '',
      },
    },
    changeBase: {
      background: '',
      word: {
        background: '',
      },
    },
    conflict: {
      handled: {
        minimapOverViewRuler: '',
      },
      handledFocused: {
        border: '',
      },
      handledUnfocused: {
        border: '',
      },
      input1: {
        background: '',
      },
      input2: {
        background: '',
      },
      unhandled: {
        minimapOverViewRuler: '',
      },
      unhandledFocused: {
        border: '',
      },
      unhandledUnfocused: {
        border: '',
      },
    },
    conflictingLines: {
      background: '',
    },
  },
  minimap: {
    background: '',
    errorHighlight: red.hexa(),
    findMatchHighlight: highlight.hexa(),
    foregroundOpacity: '',
    selectionHighlight: '',
    selectionOccurrenceHighlight: '',
    warningHighlight: '',
  },
  minimapGutter: {
    addedBackground: green.hexa(),
    deletedBackground: '',
    modifiedBackground: secondary.hexa(),
  },
  minimapSlider: {
    activeBackground: '',
    background: '',
    hoverBackground: '',
  },
  notebook: {
    cellBorderColor: '',
    cellEditorBackground: '',
    cellHoverBackground: '',
    cellInsertionIndicator: '',
    cellStatusBarItemHoverBackground: '',
    cellToolbarSeparator: '',
    editorBackground: '',
    focusedCellBackground: '',
    focusedCellBorder: '',
    focusedEditorBorder: '',
    inactiveFocusedCellBorder: '',
    inactiveSelectedCellBorder: '',
    outputContainerBackgroundColor: '',
    outputContainerBorderColor: '',
    selectedCellBackground: '',
    selectedCellBorder: '',
    symbolHighlightBackground: '',
  },
  notebookScrollbarSlider: {
    activeBackground: '',
    background: '',
    hoverBackground: '',
  },
  notebookStatusErrorIcon: {
    foreground: '',
  },
  notebookStatusRunningIcon: {
    foreground: '',
  },
  notebookStatusSuccessIcon: {
    foreground: '',
  },
  notificationCenter: {
    border: '',
  },
  notificationCenterHeader: {
    background: '',
    foreground: '',
  },
  notificationLink: {
    foreground: '',
  },
  notifications: {
    background: '',
    border: '',
    foreground: '',
  },
  notificationsErrorIcon: {
    foreground: '',
  },
  notificationsInfoIcon: {
    foreground: '',
  },
  notificationsWarningIcon: {
    foreground: '',
  },
  notificationToast: {
    border: '',
  },
  panel: {
    background: bg.hexa(),
    border: border.hexa(),
    dropBorder: '',
  },
  panelInput: {
    border: '',
  },
  panelSection: {
    border: '',
    dropBackground: highlight.opaquer(0.3).hexa(),
  },
  panelSectionHeader: {
    background: '',
    border: '',
    foreground: '',
  },
  panelTitle: {
    activeBorder: primary.hexa(),
    activeForeground: fg.hexa(),
    inactiveForeground: comment.hexa(),
  },
  peekView: {
    border: '',
  },
  peekViewEditor: {
    background: '',
    matchHighlightBackground: '',
    matchHighlightBorder: '',
  },
  peekViewEditorGutter: {
    background: '',
  },
  peekViewResult: {
    background: '',
    fileForeground: '',
    lineForeground: '',
    matchHighlightBackground: '',
    selectionBackground: '',
    selectionForeground: '',
  },
  peekViewTitle: {
    background: '',
  },
  peekViewTitleDescription: {
    foreground: '',
  },
  peekViewTitleLabel: {
    foreground: '',
  },
  pickerGroup: {
    border: '',
    foreground: '',
  },
  ports: {
    iconRunningProcessForeground: '',
  },
  problemsErrorIcon: {
    foreground: '',
  },
  problemsInfoIcon: {
    foreground: '',
  },
  problemsWarningIcon: {
    foreground: '',
  },
  progressBar: {
    background: '',
  },
  quickInput: {
    background: '',
    foreground: '',
    list: {
      focusBackground: '',
    },
  },
  quickInputList: {
    focusBackground: '',
    focusForeground: '',
    focusIconForeground: '',
  },
  quickInputTitle: {
    background: '',
  },
  sash: {
    hoverBorder: '',
  },
  scm: {
    providerBorder: '',
  },
  scrollbar: {
    shadow: none.hexa(),
  },
  scrollbarSlider: {
    activeBackground: primary.fade(0.9).hexa(),
    background: secondary.fade(0.9).hexa(),
    hoverBackground: secondary.fade(0.8).hexa(),
  },
  searchEditor: {
    findMatchBackground: highlight.hexa(),
    findMatchBorder: '',
    textInputBorder: '',
  },
  selection: {
    background: '',
  },
  settings: {
    checkboxBackground: '',
    checkboxBorder: '',
    checkboxForeground: '',
    dropdownBackground: '',
    dropdownBorder: '',
    dropdownForeground: '',
    dropdownListBorder: '',
    focusedRowBackground: '',
    focusedRowBorder: '',
    headerBorder: '',
    headerForeground: '',
    modifiedItemIndicator: '',
    numberInputBackground: '',
    numberInputBorder: '',
    numberInputForeground: '',
    rowHoverBackground: '',
    sashBorder: '',
    textInputBackground: '',
    textInputBorder: '',
    textInputForeground: '',
  },
  sideBar: {
    background: bg.darken(0.2).hexa(),
    border: border.hexa(),
    dropBackground: '',
    foreground: fg.hexa(),
  },
  sideBarSectionHeader: {
    background: bg.darken(0.2).hexa(),
    border: border.hexa(),
    foreground: fg.hexa(),
  },
  sideBarTitle: {
    foreground: fg.hexa(),
  },
  sideBySideEditor: {
    horizontalBorder: '',
    verticalBorder: '',
  },
  statusBar: {
    background: bg.darken(0.2).hexa(),
    border: border.hexa(),
    debuggingBackground: highlight.opaquer(0.3).hexa(),
    debuggingBorder: '',
    debuggingForeground: '',
    focusBorder: '',
    foreground: fg.hexa(),
    noFolderBackground: '',
    noFolderBorder: '',
    noFolderForeground: '',
  },
  statusBarItem: {
    activeBackground: '',
    compactHoverBackground: '',
    errorBackground: '',
    errorForeground: '',
    focusBorder: '',
    hoverBackground: '',
    prominentBackground: '',
    prominentForeground: '',
    prominentHoverBackground: '',
    remoteBackground: '',
    remoteForeground: '',
    warningBackground: '',
    warningForeground: '',
  },
  symbolIcon: {
    arrayForeground: '',
    booleanForeground: '',
    classForeground: '',
    colorForeground: '',
    constantForeground: '',
    constructorForeground: '',
    enumeratorForeground: '',
    enumeratorMemberForeground: '',
    eventForeground: '',
    fieldForeground: '',
    fileForeground: '',
    folderForeground: '',
    functionForeground: '',
    interfaceForeground: '',
    keyForeground: '',
    keywordForeground: '',
    methodForeground: '',
    moduleForeground: '',
    namespaceForeground: '',
    nullForeground: '',
    numberForeground: '',
    objectForeground: '',
    operatorForeground: '',
    packageForeground: '',
    propertyForeground: '',
    referenceForeground: '',
    snippetForeground: '',
    stringForeground: '',
    structForeground: '',
    textForeground: '',
    typeParameterForeground: '',
    unitForeground: '',
    variableForeground: '',
  },
  tab: {
    activeBackground: bg.hexa(),
    activeBorder: '',
    activeBorderTop: '',
    activeForeground: fg.hexa(),
    activeModifiedBorder: '',
    border: '',
    hoverBackground: bg.hexa(),
    hoverBorder: '',
    hoverForeground: '',
    inactiveBackground: bg.darken(0.2).hexa(),
    inactiveForeground: fg.hexa(),
    inactiveModifiedBorder: '',
    lastPinnedBorder: '',
    unfocusedActiveBackground: '',
    unfocusedActiveBorder: '',
    unfocusedActiveBorderTop: '',
    unfocusedActiveForeground: fg.hexa(),
    unfocusedActiveModifiedBorder: '',
    unfocusedHoverBackground: bg.hexa(),
    unfocusedHoverBorder: '',
    unfocusedHoverForeground: '',
    unfocusedInactiveBackground: bg.darken(0.2).hexa(),
    unfocusedInactiveForeground: fg.hexa(),
    unfocusedInactiveModifiedBorder: '',
  },
  terminal: {
    ansiBlack: bg.hexa(),
    ansiBlue: blue.hexa(),
    ansiBrightBlack: bg.hexa(),
    ansiBrightBlue: blue.hexa(),
    ansiBrightCyan: cyan.hexa(),
    ansiBrightGreen: green.hexa(),
    ansiBrightMagenta: pink.hexa(),
    ansiBrightRed: red.hexa(),
    ansiBrightWhite: fg.hexa(),
    ansiBrightYellow: yellow.hexa(),
    ansiCyan: cyan.hexa(),
    ansiGreen: green.hexa(),
    ansiMagenta: pink.hexa(),
    ansiRed: red.hexa(),
    ansiWhite: fg.hexa(),
    ansiYellow: yellow.hexa(),
    background: '',
    border: '',
    dropBackground: '',
    findMatchBackground: '',
    findMatchBorder: '',
    findMatchHighlightBackground: '',
    findMatchHighlightBorder: '',
    foreground: fg.hexa(),
    inactiveSelectionBackground: '',
    selectionBackground: primary.fade(0.65).hexa(),
    selectionForeground: '',
    tab: {
      activeBorder: '',
    },
  },
  terminalCommandDecoration: {
    defaultBackground: '',
    errorBackground: '',
    successBackground: '',
  },
  terminalCursor: {
    background: '',
    foreground: '',
  },
  terminalOverviewRuler: {
    cursorForeground: '',
    findMatchForeground: '',
  },
  testing: {
    iconErrored: '',
    iconFailed: '',
    iconPassed: '',
    iconQueued: '',
    iconSkipped: '',
    iconUnset: '',
    message: {
      error: {
        decorationForeground: '',
        lineBackground: '',
      },
      info: {
        decorationForeground: '',
        lineBackground: '',
      },
    },
    peekBorder: '',
    peekHeaderBackground: '',
    runAction: '',
  },
  textBlockQuote: {
    background: '',
    border: '',
  },
  textCodeBlock: {
    background: '',
  },
  textLink: {
    activeForeground: '',
    foreground: '',
  },
  textPreformat: {
    foreground: '',
  },
  textSeparator: {
    foreground: '',
  },
  titleBar: {
    activeBackground: bg.darken(0.2).hexa(),
    activeForeground: fg.hexa(),
    border: border.hexa(),
    inactiveBackground: bg.darken(0.2).hexa(),
    inactiveForeground: fg.hexa(),
  },
  toolbar: {
    activeBackground: '',
    hoverBackground: '',
    hoverOutline: '',
  },
  tree: {
    indentGuidesStroke: none.hexa(),
    tableColumnsBorder: '',
    tableOddRowsBackground: '',
  },
  walkThrough: {
    embeddedEditorBackground: '',
  },
  welcomePage: {
    background: '',
    progress: {
      background: '',
      foreground: '',
    },
    tileBackground: '',
    tileHoverBackground: '',
    tileShadow: '',
  },
  widget: {
    shadow: none.hexa(),
  },
  window: {
    activeBorder: '',
    inactiveBorder: '',
  },
};

export default Object.entries(flattenKeys(workbench)).reduce(
  (all, [key, val]) => ({ ...all, [key]: val ? val : undefined }),
  {}
);
